### ISSUE TITLE
Commandline options aren't recognized

### ISSUE THREAD

**Issue by bemeyert** [grobian/carbon-c-relay#226]
I had two occurrences where carbon-c-relay did not use the given command line options.

1. I wanted to run carbon-c-relay with option `-S 10` and the initial command line was `/usr/bin/carbon-c-relay -f /etc/carbon-c-relay.conf -p 2003 -w 4 -b 2500 -q 25000 -S 10`. According to `ps` the process was running with these option, but it still delivered in a 60 seconds interval. After I put `-S 10` to the beginning of the options it worked: `-S 10 -p 2003 -w 4 -b 2500 -q 25000`

2. The queue size was to small and I had to change it from the default of 25.000 to 420.000. The command line looks like this: `/usr/bin/carbon-c-relay -f /etc/carbon-c-relay.conf -S 10 -q 420000 -p 2003 -w 4 -b 2500`. But the change didn't take effect. In a test I saw that the queue was still limited to 25k. The log tells the same story:
```
[...]
Nov  3 09:43:10 mon-crelay-sto01 carbon-c-relay: [2016-11-03 09:43:10] starting carbon-c-relay v2.2 (2016-09-16), pid=23602
Nov  3 09:43:10 mon-crelay-sto01 carbon-c-relay: configuration:
Nov  3 09:43:10 mon-crelay-sto01 carbon-c-relay: relay hostname = mon-crelay-sto01
Nov  3 09:43:10 mon-crelay-sto01 carbon-c-relay: listen port = 2003
Nov  3 09:43:10 mon-crelay-sto01 carbon-c-relay: workers = 6
Nov  3 09:43:10 mon-crelay-sto01 carbon-c-relay: send batch size = 2500
Nov  3 09:43:10 mon-crelay-sto01 carbon-c-relay: server queue size = 25000
Nov  3 09:43:10 mon-crelay-sto01 carbon-c-relay: server max stalls = 4
Nov  3 09:43:10 mon-crelay-sto01 carbon-c-relay: statistics submission interval = 10s
Nov  3 09:43:10 mon-crelay-sto01 carbon-c-relay: listen backlog = 32
Nov  3 09:43:10 mon-crelay-sto01 carbon-c-relay: server connection IO timeout = 600ms
Nov  3 09:43:10 mon-crelay-sto01 carbon-c-relay: routes configuration = /etc/carbon-c-relay.conf
[...]
```

In both cases I used the file `/etc/sysconfig/carbon-c-relay` to set the options. This file is used as EnvironmentFile by Systemd. The process table shows the correct options.
Contents of `/etc/sysconfig/carbon-c-relay`:
```
ARGS="-S 10 -q 420000 -p 2003 -w 4 -b 2500"
```
Process according to `ps`:
```
$ ps -ef | grep re[l]ay
carbon-+ 14925     1  5 Nov02 ?        00:56:31 /usr/bin/carbon-c-relay -f /etc/carbon-c-relay.conf -S 10 -q 420000 -p 2003 -w 4 -b 2500
```

The version is *carbon-c-relay v2.2 (2016-09-16)* from EPEL on CentOS 7.

Am I doing something wrong here? Or is there an order to the command line options I'm not aware of? Any help would be much appreciated.

Thanks

**Comment by piotr1212** [comment]
Are you using carbon-c-relay-2.2-1? There is a bug in the systemd service
which is fixed in 2.2-2

Op 3 nov. 2016 10:04 a.m. schreef "bemeyert" <notifications@github.com>:

**Comment by bemeyert** [comment]
@piotr1212 Our version is 2.2.2.el7.

**Comment by piotr1212** [comment]
This is exactly the issue which was in the systemd service file in carbon-c-relay-2.2-1.el7. This was solved in carbon-c-relay-2.2-2.el7.
Could you post the content of /usr/lib/systemd/system/carbon-c-relay.service ?
You don't happen to have a custom service file in /etc/systemd/system/ or in one of the other locations?

**Comment by bemeyert** [comment]
Yes and Yes ;)

Here the service file:
```
[Unit]
Description=Enhanced C implementation of Carbon relay, aggregator and rewriter

[Service]
User=carbon-c-relay
Type=simple
EnvironmentFile=-/etc/sysconfig/carbon-c-relay
ExecStart=/usr/bin/carbon-c-relay -f /etc/carbon-c-relay.conf ${ARGS}
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
And we use our own. I just remembered that we had problems with this file (Maybe because we hit above bug).

**Comment by piotr1212** [comment]
Is that the content of /usr/lib/systemd/system/carbon-c-relay.service or is that your own file?
Are you really running carbon-c-relay-2.2-2.el7?

The issue is in the ${ARGS} this should be $ARGS without the curly braces.

**Comment by bemeyert** [comment]
I just tried the original service file from the RPM `carbon-c-relay-2.2-2.el7.x86_64.rpm` which looks like this:
```
Unit]
Description=Enhanced C implementation of Carbon relay, aggregator and rewriter
After=network.target

[Service]
User=carbon-c-relay
Type=simple
EnvironmentFile=-/etc/sysconfig/carbon-c-relay
ExecStart=/usr/bin/carbon-c-relay -f /etc/carbon-c-relay.conf $ARGS
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
It still doesn't work:
```
Nov  3 16:28:45 mon-crelay-sto01 carbon-c-relay: configuration:
Nov  3 16:28:45 mon-crelay-sto01 carbon-c-relay: relay hostname = mon-crelay-sto01
Nov  3 16:28:45 mon-crelay-sto01 carbon-c-relay: listen port = 2003
Nov  3 16:28:45 mon-crelay-sto01 carbon-c-relay: workers = 6
Nov  3 16:28:45 mon-crelay-sto01 carbon-c-relay: send batch size = 2500
Nov  3 16:28:45 mon-crelay-sto01 carbon-c-relay: server queue size = 25000
Nov  3 16:28:45 mon-crelay-sto01 carbon-c-relay: server max stalls = 4
Nov  3 16:28:45 mon-crelay-sto01 carbon-c-relay: statistics submission interval = 10s
Nov  3 16:28:45 mon-crelay-sto01 carbon-c-relay: listen backlog = 32
Nov  3 16:28:45 mon-crelay-sto01 carbon-c-relay: server connection IO timeout = 600ms
Nov  3 16:28:45 mon-crelay-sto01 carbon-c-relay: routes configuration = /etc/carbon-c-relay.conf
```
The process:
```

**Comment by piotr1212** [comment]
just to verify, you did delete the local files and run a systemctl daemon-reload?

**Comment by bemeyert** [comment]
Ok, I wrote above comment while you posted yours. I changed `${ARGS}` to `$ARGS`, did a daemon-reload, restarted and it looks like it worked. My bad. Looks like I implemented a faulty service file.

Thanks a lot for your help
